import type { AIAnalysis } from '@/lib/types';

interface AnalysisPanelProps {
  analysis: AIAnalysis;
}

export default function AnalysisPanel({ analysis }: AnalysisPanelProps) {
  const paragraphs = analysis.fullAnalysis.split('\n\n').filter(Boolean);

  return (
    <div className="rounded-lg border border-oil-800 bg-oil-900/30">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-oil-800 px-5 py-3">
        <div className="flex items-center gap-2">
          <span className="text-base">🤖</span>
          <h2 className="text-sm font-semibold text-white">AI Analysis</h2>
        </div>
        <span className="text-xs text-gray-500 font-mono">
          {analysis.model !== 'none' && analysis.model !== 'placeholder'
            ? `Claude · ${new Date(analysis.generatedAt).toLocaleDateString(
                'en-GB',
                { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' }
              )}`
            : 'Awaiting data'}
        </span>
      </div>

      <div className="p-5">
        {/* Key points */}
        {analysis.keyPoints.length > 0 && (
          <div className="mb-5 space-y-2">
            {analysis.keyPoints.map((point, i) => (
              <div key={i} className="flex items-start gap-2">
                <span className="text-oil-400 mt-0.5 text-xs">●</span>
                <span className="text-sm text-gray-300">{point}</span>
              </div>
            ))}
          </div>
        )}

        {/* Full analysis */}
        <div className="space-y-4">
          {paragraphs.map((p, i) => (
            <p key={i} className="text-sm text-gray-400 leading-relaxed">
              {p}
            </p>
          ))}
        </div>

        {/* Disclaimer */}
        <p className="mt-5 text-xs text-gray-600 italic">
          This analysis is generated by AI and may contain errors. It is not
          financial or safety advice. Always verify critical decisions with
          official sources including Eurostat, DG Energy, and your national
          energy agency.
        </p>
      </div>
    </div>
  );
}
